export const ORDERS_LOADING = "ORDERS_LOADING";
export const ORDERS_FORM_SUBMIT = "ORDERS_FORM_SUBMIT";
export const ORDERS_FORM_HTTP_REQUEST = "ORDERS_FORM_HTTP_REQUEST";
export const ORDERS_ADD = "ORDERS_ADD";
export const ORDERS_GET_PAGINATED_LIST = "ORDERS_GET_PAGINATED_LIST";
export const ORDERS_DELETE = "ORDERS_DELETE";
export const ORDERS_PAGNIATION_UPDATE = "ORDERS_PAGNIATION_UPDATE";
export const ORDERS_SUCCESS_TOAST = "ORDERS_SUCCESS_TOAST";
export const ORDERS_GET = "ORDERS_GET";
export const ORDERS_LAYOUT_STYLE = "ORDERS_LAYOUT_STYLE";
export const ORDERS_UPDATE = "ORDERS_UPDATE";
export const ORDERS_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "ORDERS_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


