export const VENDORS_LOADING = "VENDORS_LOADING";
export const VENDORS_FORM_SUBMIT = "VENDORS_FORM_SUBMIT";
export const VENDORS_FORM_HTTP_REQUEST = "VENDORS_FORM_HTTP_REQUEST";
export const VENDORS_ADD = "VENDORS_ADD";
export const VENDORS_GET_PAGINATED_LIST = "VENDORS_GET_PAGINATED_LIST";
export const VENDORS_DELETE = "VENDORS_DELETE";
export const VENDORS_PAGNIATION_UPDATE = "VENDORS_PAGNIATION_UPDATE";
export const VENDORS_SUCCESS_TOAST = "VENDORS_SUCCESS_TOAST";
export const VENDORS_GET = "VENDORS_GET";
export const VENDORS_LAYOUT_STYLE = "VENDORS_LAYOUT_STYLE";
export const VENDORS_UPDATE = "VENDORS_UPDATE";
export const VENDORS_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "VENDORS_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


