export const UPDATE_APP_ALIGNMENT = "UPDATE_APP_ALIGNMENT"
export const GLOBAL_TOAST = "GLOBAL_TOAST"


export const COMMENT_LOADING = "COMMENT_LOADING"
export const COMMENT_ERROR = "COMMENT_ERROR"
export const COMMENT_SUCCESS = "COMMENT_SUCCESS"
export const ADD_COMMENT = "ADD_COMMENT"
export const UPDATE_COMMENT = "UPDATE_COMMENT"
export const REMOVE_COMMENT = "REMOVE_COMMENT"
export const ADD_ARTICLE = "ADD_ARTICLE"
export const REMOVE_ARTICLE = "REMOVE_ARTICLE"

export const LOGGED_IN_USER = "LOGGED_IN_USER"
export const LOGGED_IN = "LOGGED_IN"
export const LOGGING = "LOGGING"
export const LOGIN_INVALID = "LOGIN_INVALID"
export const LOG_OUT = "LOG_OUT"

/**
 * todo delete MENU_LOADING, MENU_LIST after refactor
 */
export const MENU_LOADING = "MENU_LOADING"
export const MENU_LIST = "MENU_LIST"



export const SOCKET_DATA_UPDATE = "SOCKET_DATA_UPDATE"

export const GET_TABLE_PRODUCT_CATEGORIES = "GET_TABLE_PRODUCT_CATEGORIES"
export const GET_PRODUCT_CATEGORIES_SUCCESS = "GET_PRODUCT_CATEGORIES_SUCCESS"


export const USER_INVITATION_LOADING = "USER_INVITATION_LOADING"
export const INVITATION_ADD = "INVITATION_ADD"
export const INVITATION_GET = "INVITATION_GET"
export const INVITATION_DELETE = "INVITATION_DELETE"
export const INVITATION_UPDATE = "INVITATION_UPDATE"
export const INVITATION_SUCCESS_GET = "INVITATION_SUCCESS_GET"
export const INVITATION_SUBMIT_BUTTON = "INVITATION_SUBMIT_BUTTON"
export const INVITATION_PAGNIATION_UPDATE = "INVITATION_PAGNIATION_UPDATE"
export const INVITATION_FORM_SUBMIT = "INVITATION_FORM_SUBMIT";
export const INVITATION_FORM_HTTP_REQUEST = "INVITATION_FORM_HTTP_REQUEST";


export const USER_INVITATION_EXPIRY_LOADING = "USER_INVITATION_EXPIRY_LOADING"
export const USER_INVITATION_EXPIRY_ADD = "USER_INVITATION_EXPIRY_ADD"
export const USER_INVITATION_EXPIRY_GET = "USER_INVITATION_EXPIRY_GET"
export const USER_INVITATION_EXPIRY_GET_TABLE = "USER_INVITATION_EXPIRY_GET_TABLE"
export const USER_INVITATION_EXPIRY_DELETE = "USER_INVITATION_EXPIRY_DELETE"
export const USER_INVITATION_EXPIRY_PAGNIATION_UPDATE = "USER_INVITATION_EXPIRY_PAGNIATION_UPDATE"
export const USER_INVITATION_EXPIRY_UPDATE = "USER_INVITATION_EXPIRY_UPDATE"
export const USER_INVITATION_EXPIRY_GET_SUCCESS = "USER_INVITATION_EXPIRY_GET_SUCCESS"
export const USER_INVITATION_FORM_SUBMIT = "USER_INVITATION_FORM_SUBMIT";
export const USER_INVITATION_FORM_HTTP_REQUEST = "USER_INVITATION_FORM_HTTP_REQUEST";

export const CONTACT_INFO_LOADING = "CONTACT_INFO_LOADING"
export const CONTACT_INFO_ADD = "CONTACT_INFO_ADD"
export const GET_CONTACT_INFO = "GET_CONTACT_INFO"
export const GET_CONTACT_INFO_SUCCESS = "GET_CONTACT_INFO_SUCCESS"

export const BRAND_LOGO_LOADING = "BRAND_LOGO_LOADING"
export const BRAND_LOGO_ADD = "BRAND_LOGO_ADD"
export const GET_BRAND_LOGO = "GET_BRAND_LOGO"
export const GET_BRAND_LOGO_SUCCESS = "GET_CONTACT_INFO_SUCCESS"

export const SHIPPING_ADDRESS_LOADING = "SHIPPING_ADDRESS_LOADING"
export const SHIPPING_ADDRESS_ADD = "SHIPPING_ADDRESS_ADD"
export const GET_SHIPPING_ADDRESS = "GET_SHIPPING_ADDRESS"
export const GET_SHIPPING_ADDRESS_SUCCESS = "GET_SHIPPING_ADDRESS_SUCCESS"

export const BILLING_INFO_LOADING = "BILLING_INFO_LOADING"
export const BILLING_INFO_ADD = "BILLING_INFO_ADD"
export const GET_BILLING_INFO = "GET_BILLING_INFO"
export const GET_BILLING_INFO_SUCCESS = "GET_BILLING_INFO_SUCCESS"

export const BILLING_ADDRESS_LOADING = "BILLING_ADDRESS_LOADING"
export const BILLING_ADDRESS_ADD = "BILLING_ADDRESS_ADD"
export const GET_BILLING_ADDRESS = "GET_BILLING_ADDRESS"
export const GET_BILLING_ADDRESS_SUCCESS = "GET_BILLING_ADDRESS_SUCCESS"


export const CONFIGURATION_LOADING = "CONFIGURATION_LOADING"
export const CONFIGURATION_UPDATE_OR_CREATE = "CONFIGURATION_UPDATE_OR_CREATE"
export const CONFIGURATION_GET_SUCCESS = "CONFIGURATION_GET_SUCCESS"


export const ALL_ROLES_LOADING = "ALL_ROLES_LOADING"
export const ALL_ROLES_ADD = "ALL_ROLES_ADD"
export const ALL_ROLES_GET = "ALL_ROLES_GET"
export const ALL_ROLES_DELETE = "ALL_ROLES_DELETE"
export const ALL_ROLES_PAGNIATION_UPDATE = "ALL_ROLES_PAGNIATION_UPDATE"
export const ALL_ROLES_UPDATE = "ALL_ROLES_UPDATE"
export const ALL_ROLES_SUCCESS_GET = "ALL_ROLES_SUCCESS_GET"



export const BRUTE_FORCE_LOADING = "BRUTE_FORCE_LOADING"
export const BRUTE_FORCE_GET = "BRUTE_FORCE_GET"
export const BRUTE_FORCE_UPDATE = "BRUTE_FORCE_UPDATE"
export const BRUTE_FORCE_DELETE = "BRUTE_FORCE_DELETE"
export const BRUTE_FORCE_PAGNIATION_UPDATE = "BRUTE_FORCE_PAGNIATION_UPDATE"
export const BRUTE_FORCE_GET_SUCCESS = "BRUTE_FORCE_GET_SUCCESS"

export const SUSPICIOUS_LOCKED_ACCOUNT_LOADING = "SUSPICIOUS_LOCKED_ACCOUNT_LOADING"
export const SUSPICIOUS_LOCKED_ACCOUNT_GET = "SUSPICIOUS_LOCKED_ACCOUNT_GET"
export const SUSPICIOUS_LOCKED_ACCOUNT_UPDATE = "SUSPICIOUS_LOCKED_ACCOUNT_UPDATE"
export const SUSPICIOUS_LOCKED_ACCOUNT_DELETE = "SUSPICIOUS_LOCKED_ACCOUNT_DELETE"
export const SUSPICIOUS_LOCKED_ACCOUNT_PAGNIATION_UPDATE = "SUSPICIOUS_LOCKED_ACCOUNT_PAGNIATION_UPDATE"
export const SUSPICIOUS_LOCKED_ACCOUNT_GET_SUCCESS = "SUSPICIOUS_LOCKED_ACCOUNT_GET_SUCCESS"

export const UNBLOCK_LOCKED_USER = "UNBLOCK_LOCKED_USER"
export const UNBLOCK_LOCKED_USER_LOADING = "UNBLOCK_LOCKED_USER_LOADING"

export const USER_PROFILE_LOADING = "USER_PROFILE_LOADING"
export const USER_PROFILE_ADD = "USER_PROFILE_ADD"
export const USER_PROFILE_UPDATE_EMAIL = "USER_PROFILE_UPDATE_EMAIL"
export const USER_PROFILE_UPDATE_PASSWORD = "USER_PROFILE_UPDATE_PASSWORD"
export const GET_USER_PROFILE = "GET_USER_PROFILE"
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS"


export const CUSTOM_FIELDS_LOADING = "CUSTOM_FIELDS_LOADING"
export const CUSTOM_FIELDS_ADD = "CUSTOM_FIELDS_ADD"
export const CUSTOM_FIELDS_GET = "CUSTOM_FIELDS_GET"
export const CUSTOM_FIELDS_DELETE = "CUSTOM_FIELDS_DELETE"
export const CUSTOM_FIELDS_PAGNIATION_UPDATE = "CUSTOM_FIELDS_PAGNIATION_UPDATE"
export const CUSTOM_FIELDS_UPDATE = "CUSTOM_FIELDS_UPDATE"
export const CUSTOM_FIELDS_SUCCESS_GET = "CUSTOM_FIELDS_SUCCESS_GET"
export const CUSTOM_FIELD_SUBMIT_BUTTON = "CUSTOM_FIELD_SUBMIT_BUTTON"
export const CUSTOM_FIELD_FORM_SUBMIT = "CUSTOM_FIELD_FORM_SUBMIT";
export const CUSTOM_FIELD_FORM_HTTP_REQUEST = "CUSTOM_FIELD_FORM_HTTP_REQUEST";



export const FORM_BUILDER_UPDATE_SCHEMA = "FORM_BUILDER_UPDATE_SCHEMA";


// Ticketing System
export const TICKETING_DEPARTMENTS_LOADING = "TICKETING_DEPARTMENTS_LOADING"
export const TICKETING_DEPARTMENTS_ADD = "TICKETING_DEPARTMENTS_ADD"
export const TICKETING_DEPARTMENTS_GET = "TICKETING_DEPARTMENTS_GET"
export const TICKETING_DEPARTMENTS_DELETE = "TICKETING_DEPARTMENTS_DELETE"
export const TICKETING_DEPARTMENTS_PAGNIATION_UPDATE = "TICKETING_DEPARTMENTS_PAGNIATION_UPDATE"
export const TICKETING_DEPARTMENTS_UPDATE = "TICKETING_DEPARTMENTS_UPDATE"
export const TICKETING_DEPARTMENTS_SUCCESS_GET = "TICKETING_DEPARTMENTS_SUCCESS_GET"
export const TICKETING_DEPARTMENT_SUBMIT_BUTTON = "TICKETING_DEPARTMENT_SUBMIT_BUTTON"
export const TICKETING_DEPARTMENTS_FORM_SUBMIT = "TICKETING_DEPARTMENTS_FORM_SUBMIT";
export const TICKETING_DEPARTMENTS_FORM_HTTP_REQUEST = "TICKETING_DEPARTMENTS_FORM_HTTP_REQUEST";

export const EMAILS_LOADING = "EMAILS_LOADING"
export const EMAILS_ADD = "EMAILS_ADD"
export const EMAILS_GET = "EMAILS_GET"
export const EMAILS_DELETE = "EMAILS_DELETE"
export const EMAILS_PAGNIATION_UPDATE = "EMAILS_PAGNIATION_UPDATE"
export const EMAILS_UPDATE = "EMAILS_UPDATE"
export const EMAILS_SUCCESS_GET = "EMAILS_SUCCESS_GET"
export const EMAIL_SUBMIT_BUTTON = "EMAIL_SUBMIT_BUTTON"
export const EMAILS_FORM_SUBMIT = "EMAILS_FORM_SUBMIT";
export const EMAILS_FORM_HTTP_REQUEST = "EMAILS_FORM_HTTP_REQUEST";

export const EMAIL_BANLIST_LOADING = "EMAIL_BANLIST_LOADING"
export const EMAIL_BANLIST_ADD = "EMAIL_BANLIST_ADD"
export const EMAIL_BANLIST_GET = "EMAIL_BANLIST_GET"
export const EMAIL_BANLIST_DELETE = "EMAIL_BANLIST_DELETE"
export const EMAIL_BANLIST_PAGNIATION_UPDATE = "EMAIL_BANLIST_PAGNIATION_UPDATE"
export const EMAIL_BANLIST_UPDATE = "EMAIL_BANLIST_UPDATE"
export const EMAIL_BANLIST_SUCCESS_GET = "EMAIL_BANLIST_SUCCESS_GET"
export const EMAIL_BANLIST_SUBMIT_BUTTON = "EMAIL_BANLIST_SUBMIT_BUTTON"
export const EMAIL_BANLIST_FORM_SUBMIT = "EMAIL_BANLIST_FORM_SUBMIT";
export const EMAIL_BANLIST_FORM_HTTP_REQUEST = "EMAIL_BANLIST_FORM_HTTP_REQUEST";

export const EMAIL_TEMPLATES_LOADING = "EMAIL_TEMPLATES_LOADING"
export const EMAIL_TEMPLATES_ADD = "EMAIL_TEMPLATES_ADD"
export const EMAIL_TEMPLATES_GET = "EMAIL_TEMPLATES_GET"
export const EMAIL_TEMPLATES_DELETE = "EMAIL_TEMPLATES_DELETE"
export const EMAIL_TEMPLATES_PAGNIATION_UPDATE = "EMAIL_TEMPLATES_PAGNIATION_UPDATE"
export const EMAIL_TEMPLATES_UPDATE = "EMAIL_TEMPLATES_UPDATE"
export const EMAIL_TEMPLATES_SUCCESS_GET = "EMAIL_TEMPLATES_SUCCESS_GET"
export const EMAIL_TEMPLATE_SUBMIT_BUTTON = "EMAIL_TEMPLATE_SUBMIT_BUTTON"
export const EMAIL_TEMPLATE_FORM_SUBMIT = "EMAIL_TEMPLATE_FORM_SUBMIT";
export const EMAIL_TEMPLATE_FORM_HTTP_REQUEST = "EMAIL_TEMPLATE_FORM_HTTP_REQUEST";

export const DEPARTMENTS_LOADING = "DEPARTMENTS_LOADING"
export const DEPARTMENTS_ADD = "DEPARTMENTS_ADD"
export const DEPARTMENTS_GET = "DEPARTMENTS_GET"
export const DEPARTMENTS_DELETE = "DEPARTMENTS_DELETE"
export const DEPARTMENTS_PAGNIATION_UPDATE = "DEPARTMENTS_PAGNIATION_UPDATE"
export const DEPARTMENTS_UPDATE = "DEPARTMENTS_UPDATE"
export const DEPARTMENTS_SUCCESS_GET = "DEPARTMENTS_SUCCESS_GET"
export const DEPARTMENT_SUBMIT_BUTTON = "DEPARTMENT_SUBMIT_BUTTON"


export const GROUPS_LOADING = "GROUPS_LOADING"
export const GROUPS_ADD = "GROUPS_ADD"
export const GROUPS_GET = "GROUPS_GET"
export const GROUPS_DELETE = "GROUPS_DELETE"
export const GROUPS_PAGNIATION_UPDATE = "GROUPS_PAGNIATION_UPDATE"
export const GROUPS_UPDATE = "GROUPS_UPDATE"
export const GROUPS_SUCCESS_GET = "GROUPS_SUCCESS_GET"
export const GROUP_SUBMIT_BUTTON = "GROUP_SUBMIT_BUTTON"
export const GROUP_FORM_SUBMIT = "GROUP_FORM_SUBMIT";
export const GROUP_FORM_HTTP_REQUEST = "GROUP_FORM_HTTP_REQUEST";

export const STAFF_MEMBERS_LOADING = "STAFF_MEMBERS_LOADING"
export const STAFF_MEMBERS_ADD = "STAFF_MEMBERS_ADD"
export const STAFF_MEMBERS_GET = "STAFF_MEMBERS_GET"
export const STAFF_MEMBERS_DELETE = "STAFF_MEMBERS_DELETE"
export const STAFF_MEMBERS_PAGNIATION_UPDATE = "STAFF_MEMBERS_PAGNIATION_UPDATE"
export const STAFF_MEMBERS_UPDATE = "STAFF_MEMBERS_UPDATE"
export const STAFF_MEMBERS_SUCCESS_GET = "STAFF_MEMBERS_SUCCESS_GET"
export const STAFF_MEMBER_SUBMIT_BUTTON = "STAFF_MEMBER_SUBMIT_BUTTON"
export const STAFF_MEMBER_FORM_SUBMIT = "STAFF_MEMBER_FORM_SUBMIT";
export const STAFF_MEMBER_FORM_HTTP_REQUEST = "STAFF_MEMBER_FORM_HTTP_REQUEST";

export const TEAMS_LOADING = "TEAMS_LOADING"
export const TEAMS_ADD = "TEAMS_ADD"
export const TEAMS_GET = "TEAMS_GET"
export const TEAMS_DELETE = "TEAMS_DELETE"
export const TEAMS_PAGNIATION_UPDATE = "TEAMS_PAGNIATION_UPDATE"
export const TEAMS_UPDATE = "TEAMS_UPDATE"
export const TEAMS_SUCCESS_GET = "TEAMS_SUCCESS_GET"
export const TEAM_SUBMIT_BUTTON = "TEAM_SUBMIT_BUTTON"
export const TEAMS_FORM_SUBMIT = "TEAMS_FORM_SUBMIT";
export const TEAMS_FORM_HTTP_REQUEST = "TEAMS_FORM_HTTP_REQUEST";
