export const USER_LOADING = "USER_LOADING";
export const USER_FORM_SUBMIT = "USER_FORM_SUBMIT";
export const USER_FORM_HTTP_REQUEST = "USER_FORM_HTTP_REQUEST";
export const USER_ADD = "USER_ADD";
export const USER_GET_PAGINATED_LIST = "USER_GET_PAGINATED_LIST";
export const USER_DELETE = "USER_DELETE";
export const USER_PAGNIATION_UPDATE = "USER_PAGNIATION_UPDATE";
export const USER_SUCCESS_TOAST = "USER_SUCCESS_TOAST";
export const USER_GET = "USER_GET";
export const USER_LAYOUT_STYLE = "USER_LAYOUT_STYLE";
export const USER_UPDATE = "USER_UPDATE";
export const USER_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "USER_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


