export const TODO_TASK_LOADING = "TODO_TASK_LOADING";
export const TODO_TASK_FORM_SUBMIT = "TODO_TASK_FORM_SUBMIT";
export const TODO_TASK_FORM_HTTP_REQUEST = "TODO_TASK_FORM_HTTP_REQUEST";
export const TODO_TASK_ADD = "TODO_TASK_ADD";
export const TODO_TASK_GET_PAGINATED_LIST = "TODO_TASK_GET_PAGINATED_LIST";
export const TODO_TASK_DELETE = "TODO_TASK_DELETE";
export const TODO_TASK_PAGNIATION_UPDATE = "TODO_TASK_PAGNIATION_UPDATE";
export const TODO_TASK_SUCCESS_TOAST = "TODO_TASK_SUCCESS_TOAST";
export const TODO_TASK_GET = "TODO_TASK_GET";
export const TODO_TASK_LAYOUT_STYLE = "TODO_TASK_LAYOUT_STYLE";
export const TODO_TASK_UPDATE = "TODO_TASK_UPDATE";
export const TODO_TASK_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "TODO_TASK_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


