import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
// import "primereact/resources/themes/lara-light-indigo/theme.css";
// import "../assets/themes/lara-light-teal/theme.css"
import "../assets/themes/lara-light-cookin/theme.css"

import { PrimeReactProvider } from "primereact/api";
import StoreProvider from "@/store/StoreProvider";
import ToastProvider from "@/component/general/ToastProvider";
import { APP_NAME } from "@/utils/constants";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrimeReactProvider>
          <StoreProvider>
            <ToastProvider>
              {children}
           </ToastProvider>
          </StoreProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
