export const DISH_LOADING = "DISH_LOADING";
export const DISH_FORM_SUBMIT = "DISH_FORM_SUBMIT";
export const DISH_FORM_HTTP_REQUEST = "DISH_FORM_HTTP_REQUEST";
export const DISH_ADD = "DISH_ADD";
export const DISH_GET_PAGINATED_LIST = "DISH_GET_PAGINATED_LIST";
export const DISH_DELETE = "DISH_DELETE";
export const DISH_PAGNIATION_UPDATE = "DISH_PAGNIATION_UPDATE";
export const DISH_SUCCESS_TOAST = "DISH_SUCCESS_TOAST";
export const DISH_GET = "DISH_GET";
export const DISH_LAYOUT_STYLE = "DISH_LAYOUT_STYLE";
export const DISH_UPDATE = "DISH_UPDATE";
export const DISH_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "DISH_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


