export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_FORM_SUBMIT = "CATEGORIES_FORM_SUBMIT";
export const CATEGORIES_FORM_HTTP_REQUEST = "CATEGORIES_FORM_HTTP_REQUEST";
export const CATEGORIES_ADD = "CATEGORIES_ADD";
export const CATEGORIES_GET_PAGINATED_LIST = "CATEGORIES_GET_PAGINATED_LIST";
export const CATEGORIES_DELETE = "CATEGORIES_DELETE";
export const CATEGORIES_PAGNIATION_UPDATE = "CATEGORIES_PAGNIATION_UPDATE";
export const CATEGORIES_SUCCESS_TOAST = "CATEGORIES_SUCCESS_TOAST";
export const CATEGORIES_GET = "CATEGORIES_GET";
export const CATEGORIES_LAYOUT_STYLE = "CATEGORIES_LAYOUT_STYLE";
export const CATEGORIES_UPDATE = "CATEGORIES_UPDATE";
export const CATEGORIES_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "CATEGORIES_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


