export const ADMIN_USER_LOADING = "ADMIN_USER_LOADING";
export const ADMIN_USER_FORM_SUBMIT = "ADMIN_USER_FORM_SUBMIT";
export const ADMIN_USER_FORM_HTTP_REQUEST = "ADMIN_USER_FORM_HTTP_REQUEST";
export const ADMIN_USER_ADD = "ADMIN_USER_ADD";
export const ADMIN_USER_GET_PAGINATED_LIST = "ADMIN_USER_GET_PAGINATED_LIST";
export const ADMIN_USER_DELETE = "ADMIN_USER_DELETE";
export const ADMIN_USER_PAGNIATION_UPDATE = "ADMIN_USER_PAGNIATION_UPDATE";
export const ADMIN_USER_SUCCESS_TOAST = "ADMIN_USER_SUCCESS_TOAST";
export const ADMIN_USER_GET = "ADMIN_USER_GET";
export const ADMIN_USER_LAYOUT_STYLE = "ADMIN_USER_LAYOUT_STYLE";
export const ADMIN_USER_UPDATE = "ADMIN_USER_UPDATE";
export const ADMIN_USER_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "ADMIN_USER_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


