export const CUISINE_LOADING = "CUISINE_LOADING";
export const CUISINE_FORM_SUBMIT = "CUISINE_FORM_SUBMIT";
export const CUISINE_FORM_HTTP_REQUEST = "CUISINE_FORM_HTTP_REQUEST";
export const CUISINE_ADD = "CUISINE_ADD";
export const CUISINE_GET_PAGINATED_LIST = "CUISINE_GET_PAGINATED_LIST";
export const CUISINE_DELETE = "CUISINE_DELETE";
export const CUISINE_PAGNIATION_UPDATE = "CUISINE_PAGNIATION_UPDATE";
export const CUISINE_SUCCESS_TOAST = "CUISINE_SUCCESS_TOAST";
export const CUISINE_GET = "CUISINE_GET";
export const CUISINE_LAYOUT_STYLE = "CUISINE_LAYOUT_STYLE";
export const CUISINE_UPDATE = "CUISINE_UPDATE";
export const CUISINE_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "CUISINE_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


